### ISSUE TITLE
Should traigebot close stale issues?

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#7]
Maybe after a long while (something to be defined) that an issue is open and is stale, we want to:

1. have triagebot posting a comment asking people to try the issue again to see if the issue is still a thing or not or to provide more information
2. people may realize the thing is fixed and we can just close or if nobody ever replies the bot after waiting for some (to be defined) time can close the issue.

**Comment by Mark-Simulacrum** [comment]
There's a desire for "close in 7 days" or something -- see https://github.com/rust-lang/triagebot/issues/2 and https://github.com/rust-lang/triagebot/issues/19 -- but I wouldn't want general closing of stale issues.

We've historically found that it's mostly not too helpful with the amount of issues we have -- for example, we have 2,788 issues as of now that are more than 6 months since the last update (https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C2020-01-01). Most of those should not be closed. Going to 1 year, we have 1,590 (https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C2019-06-26) issues so that's also insufficient.

**Comment by spastorino** [comment]
@Mark-Simulacrum yeah, the idea of this issue was to start a discussion about this. Also maybe my description is a bit confusing but I wouldn't blindly close issues, the idea was to notify the reporters that the issue is stale first but maybe that's the only thing we want to do. I meant, once a bot notifies that the issue is stale, maybe even tag it as stale and ask if this is still an issue today, somebody at some point will notice and decide if the issue is still appropriate or not and then close it. Maybe that's a better schema than just closing things.

**Comment by Mark-Simulacrum** [comment]
I don't think *any* notification that's time based makes sense, including labeling the issue - we have thousands of issues that are "stale" but should be kept around. I would prefer to avoid every one of those issues getting pings or labeled for triage every 6 months or whatever - it seems pretty high effort for little gain. We can mostly use the updated GitHub search if someone wants to do this noiselessly.

**Comment by spastorino** [comment]
Fair enough :+1: and what you say makes sense, let's close this issue then.
